version: '3.3'

services:
  postgres:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_trasactions_data:/var/lib/postgresql/data

volumes:
  postgres_trasactions_data:
