version: '3.3'

services:
  postgres:
    image: postgres:14.7-alpine
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_trasactions_data:/var/lib/postgresql/data

volumes:
  postgres_trasactions_data:
